name: petronexus
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.7
  fluttertoast: ^8.2.10
  fbdb: ^1.3.2
  http: ^1.3.0
  flutter_spinkit: ^5.1.0 
  intl: ^0.17.0
  pdf: ^3.10.4
  excel: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/oil.jpg
    - assets/images/lateral.jpg

  fonts:
    - family: Roboto # Nombre de la familia de fuentes
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf